format = """
[░▒](#a3aed2)\
[](bg:#769ff0 fg:#a3aed2)\
$username\
[](fg:#769ff0 bg:#5f7acc)\
$hostname\
[](fg:#5f7acc bg:#394260)\
$directory\
[](fg:#394260 bg:#212736)\
$git_branch\
$git_status\
[](fg:#212736 bg:#1d2230)\
$python\
$virtualenv\
$nodejs\
$rust\
$golang\
$php\
$time\
$cmd_duration\
$character
"""

[username]
style_user = "fg:#090c0c bg:#769ff0"
style_root = "fg:#090c0c bg:#769ff0"
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname](bold fg:#090c0c bg:#5f7acc)'
trim_at = '-'
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#394260"
format = "[:$path]($style)"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " \ue725"
style = "bg:#212736"
format = '[[$symbol $branch](fg:#769ff0 bg:#212736)]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bg:#212736 fg:#769ff0"
conflicted = "󰞇"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "+${count}"
stashed = "󰏖"
modified = "!${count}"
staged = "+${count}"
renamed = "󰬴${count}"
deleted = "󰮉${count}"
ignore_submodules = true

[python]
symbol = "\ue606"
style = "bg:#1d2230"
format = '([[ $symbol ($version)](fg:#769ff0 bg:#1d2230)]($style))'

[virtualenv]
symbol = ""
style = "bg:#1d2230"
format = '([[ $symbol ($name)](fg:#769ff0 bg:#1d2230)]($style))'

[nodejs]
symbol = "\ued0d"
style = "bg:#1d2230"
format = '([[ $symbol ($version)](fg:#769ff0 bg:#1d2230)]($style))'

[rust]
symbol = "\ue7a8"
style = "bg:#1d2230"
format = '([[ $symbol ($version)](fg:#769ff0 bg:#1d2230)]($style))'

[golang]
symbol = "\uf1a0"
style = "bg:#1d2230"
format = '([[ $symbol ($version)](fg:#769ff0 bg:#1d2230)]($style))'

[php]
symbol = "\ue73d"
style = "bg:#1d2230"
format = '([[ $symbol ($version)](fg:#769ff0 bg:#1d2230)]($style))'

[cmd_duration]
min_time = 100
format = "[ $duration](fg:#769ff0 bg:#1d2230)"
show_milliseconds = true
style = "fg:#769ff0 bg:#1d2230"

[time]
time_format = "%R"
style = "bg:#1d2230"
format = '[[ $time](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[character]
success_symbol = " [❯](green)"
error_symbol = " [❯](bold red)"
