import = [
  "~/.config/alacritty/themes/iterm.toml"
]

[window.dimensions]
columns = 130
lines = 70

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste"},
]

[window]
dynamic_padding = true
opacity = 0.97

[font]
size = 12.75

[font.bold]
family = "GoMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "GoMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "GoMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "GoMono Nerd Font"
style = "Medium"

